export default {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  LOGOUT: "LOGOUT",

  FRIENDS_REQUEST: "FRIENDS_REQUEST",
  FRIENDS_SUCCESS: "FRIENDS_SUCCESS",
  FRIENDS_FAILURE: "FRIENDS_FAILURE"
};
